Repository Kernel360/KBE5_HomeAid_FE, pull requests merged in 2025-07, with the labels that each got.

#68 [Refactor] 페이징, 리뷰 상세페이지 수정
  src/features/admin/pages/CustomerList.jsx
  src/features/admin/pages/Inquiries.jsx
  src/features/admin/pages/ManagerList.jsx
  src/features/admin/pages/MatchingManagement.jsx
  src/features/admin/pages/ReviewManagement.jsx
Labels: enhancement

#69 [Refactor] 예약 상세정보에 매니저 아이디 추가, 관리자 수요자 조회 페이지 버그 수정
  src/features/admin/pages/CustomerList.jsx
  src/features/main/UserReservationDetail.jsx
Labels: bug

#71 [Feature] 매니저 서류 업로드 UI/UX 개선
  src/api/index.js
  src/features/mypage/manager/components/ManagerDocumentUpload.css
  src/features/mypage/manager/components/ManagerDocumentUpload.jsx
Labels: enhancement

#76 [Feature] #75 매니저 서류 파일 다운로드 기능 추가
  src/features/admin/components/ManagerDetailModal.jsx
Labels: enhancement

#81 [Refactor] 관리자 통계 연/월/일 단위 확장 및 구조리팩토링
  src/features/admin/components/AdminPaymentDetail.jsx
  src/features/admin/components/ChartSection.jsx
  src/features/admin/components/DateSelector.jsx
  src/features/admin/components/DistributionChart.jsx
  src/features/admin/components/SettlementDetailModal.jsx
  src/features/admin/components/TabNavigation.jsx
  src/features/admin/components/layout/Header.jsx
  src/features/admin/data/statisticsData.jsx
  src/features/admin/pages/CustomerPayment.jsx
  src/features/admin/pages/Dashboard.jsx
  src/features/admin/pages/Inquiries.jsx
  src/features/admin/pages/ManagerSettlement.jsx
  src/features/admin/pages/Statistics.jsx
  src/features/admin/services/statisticsAPI.js
  src/features/admin/utils/statisticsUtils.js
Labels: enhancement

#83 [Feature] Google OAuth 로그인 기능 구현
  src/features/auth/AdditionalProfilePage.jsx
  src/features/auth/OAuthCallbackPage.jsx
  src/features/auth/SignInPage.jsx
  src/features/auth/routes/index.jsx
  src/features/auth/services/authService.js
  src/main.jsx
Labels: enhancement

#79 [Refactor] 체크인 체크아웃 API 수정
  src/api/index.js
  src/features/main/UserReservationDetail.jsx
  src/features/matching/hooks/useMatchingActions.js
  src/features/matching/hooks/useMatchingData.js
  src/features/matching/pages/ManagerServiceCheckIn.jsx
Labels: documentation

#85 [Refactor] Oauth 기능 수정 및 추가 정보 입력 폼 ui 수정
  src/api/config/api.js
  src/features/auth/AdditionalProfilePage.jsx
  src/features/auth/OAuthCallbackPage.jsx
  src/features/auth/services/authService.js
Labels: enhancement

#89 [chore] ui 일부 수정
  src/api/index.js
  src/features/admin/components/AdminPaymentDetail.jsx
  src/features/admin/components/ChartSection.jsx
  src/features/admin/components/TabNavigation.jsx
  src/features/admin/components/layout/Sidebar.jsx
  src/features/admin/pages/ManagerSettlement.jsx
  src/features/main/UserReservationDetail.jsx
  src/features/main/UserReservationList.jsx
  src/features/matching/pages/ManagerMatchingRequest.jsx
  src/features/mypage/manager/pages/ManagerMypage.jsx
Labels: documentation
